version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: fitnessmealplanner-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - fitmeal-network

  createbucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      mc mb myminio/fitnessmealplanner-recipes --ignore-existing;
      mc anonymous set public myminio/fitnessmealplanner-recipes;
      exit 0;
      "
    networks:
      - fitmeal-network

volumes:
  minio_data:

networks:
  fitmeal-network:
    external: true
    name: fitnessmealplanner_default